---
- name: expose WSID identity
  blockinfile:
    path: "{{ nginx_le_configs_directory }}/default.conf"
    block: |
        
        # expose wsid identity
        include {{ wsid_includes_dir }}/nginx-expose.conf ;
    insertafter: "\s+include /etc/nginx/ssl_params ;"
- name: wait for letsencrypt cert to be generated
  delay: 15
  wait_for:
    path: "{{ nginx_le_install_dir }}/data/storage/letsencrypt/etc/live/prod/fullchain.pem"
- name: wait for WSID identity to be generated
  wait_for:
    path: "{{ wsid_var_run }}/public/passwdhash"
- name: wait for SSL to come up
  wait_for:
    port: 443
